name: secret-workflow

on:
  push:

jobs:  
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bash Script
        env:
          MY_API_KEY: ${{ secrets.SECRET }}
        run: echo "The secret is ${{ secrets.SECRET }}"
