name: secret-workflow

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bash Script
        env:
          SECRET_VALUE: ${{ secrets.SECRET }}
        run: echo "The secret is \${{ secrets.SECRET }}"
